apiVersion: v1
kind: Service
metadata:
  name: executus-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: executus-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081